fun main(){
    var num= mutableListOf(1,2,3,4,5)
    println(num)
    println()
    println(num.size)
    println("==============")
    println(num.drop(3))
    println()
    println(num.dropLast(3))
    println()
    println(num.dropWhile { it <3})
    println("==============")
    println(num.filter { it > 3})
    println()
    println(num.filterNot { it > 3})
    println("==============")
    println(num.take(3))
    println()
    println(num.takeLast(3))
    println()
    println(num.takeWhile { it >3})
    println()
    println(num.takeLastWhile { it < 3})
}